### ISSUE TITLE
RuntimeError: VCF file is missing mandatory header line ("#CHROM...") 

### ISSUE THREAD

**Issue by ChenJuiYANG** [ksamuk/pixy#98]
I got an error message when I run pixy. 

"_RuntimeError: VCF file is missing mandatory header line ("#CHROM...")_"

However, I am pretty sure my input vcf file have the "#CHROM.." line in the header. 
In fact, I ran pixy parallelly with different small chunks. The input files were made at the same time with the same protocol. Most  runs were fine, but there about 3 (of 56) runs report the error message above. 
In those failed runs, pixy gave some extra warning message: 
"_[W::hts_idx_load2] The index file is older than the data file: [CSI INDEX FILE PATH]_"

I have both csi and bai index file for each vcf file. The csi index is produced at the same time with vcf files, not older. I think the error is because pixy tried to read csi index rather than tbi index in those failed runs, and pixy may have some trouble in reading csi format index. 
So I moved all csi index to other place and ran pixy again. Interestingly, it worked well. 

If this issue has been solved in the newer version, feel free to close the issue. 

Command used:
```
pixy --stats pi fst dxy \
--vcf ${vcf} --output_folder pixyOutput/ --output_prefix pixy.${chr}.out \
--populations ID_SP.list --chromosomes "${chr}" --bypass_invariant_check yes \
--window_size 100000 --n_cores 4 
```

Version:
1.2.5.beta1

OS:
linux

**Comment by ksamuk** [comment]
Hi There,

Yes, .csi indexes are not currently supported, although are a planned feature. 

Cheers,

Kieran

**Comment by ChenJuiYANG** [comment]
Thanks for the prompt reply.

I mean this should be a bug. If .csi index is not supported, it should always use/find .tbi index when both index files exist.
As I mentioned, most tasks worked well but sometimes just not.

Chen-Jui

**Comment by ksamuk** [comment]
Hi Chen-Jui,

I agree, although this is bit of an unusual edge case, since usually there would be a single index. I'd be happy to review a pull request if you'd like to implement a fix for this feature. 

Cheers,

Kieran

**Comment by ChenJuiYANG** [comment]
Hi Kieran, 

I agree this is probably a rare case, and the error could simply be solved by move the .csi index somewhere else. I think I will just leave this issue here, and hopefully someone who has the same problem in the future may find this discussion. 

The reason I have both format of index is because I used bcftools to concatenate the invariant parts and the variant parts. The bcftools can produce an index file at the same time while concatenating vcf files, while it is in .csi format by default. Unfortunately, some programs, including pixy, don't support .csi format, so I re-indexed the vcf files with .tbi format and left the .csi index in the same place. 


Chen-Jui

**Comment by Turbo-best-version-ever** [comment]
Hi ksamuk

I encountered the same issue as described above, with one difference: I did not prepare a csi index but only a tbi index, yet the problem still occurred.
Moreover, the frequency was not as low as mentioned. I have tried running the analysis around 10 times over the past two days with different n_cores settings, and the same error popped up every single time. However, I confirmed that the chromosome causing the error did not actually have the problem of "VCF file is missing mandatory header line ("#CHROM...")". Additionally, I verified that the analysis could run successfully for this chromosome when using n_cores = 1. 

I wonder if there might be some other underlying causes for this issue.

As I conducted more attempts, the error that originally only occurred on the last chromosome now started popping up on every single chromosome.

**Comment by Turbo-best-version-ever** [comment]
Here is my bash script :

mkdir -p output_pixy

for i in {1..12}
do
/home/miniconda3/envs/pixy/bin/pixy \
--stats pi dxy fst \
--vcf Chr${i}.basic.revhet.mis07.recode.vcf.gz \
--bypass_invariant_check yes \
--pop 232_sample_list \
--window_size 10000 \
--n_cores 100 \
--output_folder output_pixy \
--output_prefix 232ind.Chr${i}
done
